# Generated by Django 4.2.5 on 2023-09-27 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Record",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField(max_length=4)),
                ("attorney", models.CharField(max_length=50)),
                ("client_description", models.CharField(max_length=500)),
                ("matter_desc", models.CharField(max_length=500)),
                ("matter_only", models.BooleanField(max_length=2)),
                ("client_num", models.IntegerField(max_length=10)),
                ("matter_num", models.IntegerField(max_length=10)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("user", models.CharField(max_length=50)),
            ],
        ),
    ]
